[package]
name = "rust_web_framework"
version = "0.1.4"
edition = "2021"
description = "Quickly crate API:s using this simple and lightweight framework."
license = "MIT"

[dependencies]
terminal-link = "0.1.0"
ansi_term = "0.12.1"